const data = {
    "user_id": 10002,
    "tenant_id": 10001,
    "role_scopes": [],
    "team_id": null,
    "event": "task_approval_updated",
    "properties": {
		"user_name":"nabeel asif",
		"task_status":"IN_PROGRESS",
		"task_title":"Data Entry",
		"client_name":"Production",
        "task": {
            "id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a",
            "task_type_id": 2,
            "client_workflow_task_id": 1646,
            "client_id": 95,
            "title": "Data Entry",
            "due_date": "2024-01-31T00:00:00.000Z",
            "is_billable": true,
            "budgeted_hours": "1.00",
            "assignee_user_id": 10046,
            "dependent_task_id": null,
            "extended_date": null,
            "is_approval_required": true,
            "approval_from": 10002,
            "status": "IN_PROGRESS",
            "repeat_type": null,
            "repeat_interval": null,
            "is_new_task_created": false,
            "is_tentative": false,
            "description": "*Add Instructions",
            "start_date": "2024-01-29T00:00:00.000Z",
            "notes": null,
            "workflow_recurrence_id": "c7055398-bee2-447b-af0e-f47ab60c63ec",
            "group_key": null,
            "dependancy_order": 0,
            "metadata": null,
            "type": null,
            "start_time": null,
            "end_time": null,
            "created_at": "2023-02-20T18:11:30.618Z",
            "updated_at": "2024-01-29T08:40:25.923Z",
            "agenda": null,
            "task_recurrence_id": null,
            "my_task": null,
            "task_recurrence": null,
            "client_workflow": {
                "id": 484,
                "workflow_id": 156,
                "client_id": 95,
                "version": 1.2,
                "is_active": true,
                "start_date": "2023-02-20T00:00:00.000Z",
                "repeat_type": "WEEKLY",
                "repeat_interval": 1,
                "created_at": "2023-02-20T18:07:55.115Z",
                "updated_at": "2023-09-15T07:21:54.804Z",
                "is_monthly_on_day": false,
                "recur_preference": null,
                "end_on": {
                    "type": "never",
                    "occurrence": null,
                    "end_date": null
                },
                "deleted": false,
                "required_days": 2,
                "status": "active",
                "display_name": "Data Entry  (2)",
                "workflow": {
                    "id": 156,
                    "name": "Data Entry ",
                    "tenant_id": 10001,
                    "created_at": "2023-09-15T07:20:56.342Z",
                    "updated_at": "2023-09-15T07:21:55.479Z",
                    "description": null,
                    "rating": null,
                    "author_id": null,
                    "deleted": false,
                    "icon_name": null,
                    "icon_image": null,
                    "color": "#792d92",
                    "category_id": 1,
                    "status": "PUBLISHED",
                    "workflow_library_id": "75617639-3891-4e71-9150-e31bb5fe2be6"
                },
                "attachment": {
                    "id": "ea736471-55d6-45a2-acad-d4382dff114e",
                    "client_workflow_id": 484,
                    "sections": {
                        "folder": {
                            "default_folder_id": "6579abc1c79606c686cee88f",
                            "attached_ids": ["6579abc1c79606c686cee88f"]
                        }
                    },
                    "created_at": "2023-12-13T13:04:02.421Z",
                    "updated_at": "2023-12-13T13:04:02.422Z"
                }
            },
            "task_assignees": [{
                "user_profile": {
                    "id": 10046,
                    "full_name": "Mohib Habib",
                    "image_url": ""
                }
            }],
            "client_workflow_task": {
                "id": 1646,
                "client_workflow_id": 484,
                "task_type_id": 2,
                "title": "Data Entry",
                "description": "*Add Instructions",
                "is_billable": true,
                "budgeted_hours": "1.00",
                "assignee_user_id": null,
                "dependent_task_id": null,
                "required_days": 2,
                "approval_from": null,
                "is_approval_required": false,
                "deleted": false,
                "order": 13,
                "client_workflow": {
                    "id": 484,
                    "workflow_id": 156,
                    "client_id": 95,
                    "version": 1.2,
                    "is_active": true,
                    "start_date": "2023-02-20T00:00:00.000Z",
                    "repeat_type": "WEEKLY",
                    "repeat_interval": 1,
                    "created_at": "2023-02-20T18:07:55.115Z",
                    "updated_at": "2023-09-15T07:21:54.804Z",
                    "is_monthly_on_day": false,
                    "recur_preference": null,
                    "end_on": {
                        "type": "never",
                        "occurrence": null,
                        "end_date": null
                    },
                    "deleted": false,
                    "required_days": 2,
                    "status": "active",
                    "display_name": "Data Entry  (2)",
                    "workflow": {
                        "id": 156,
                        "name": "Data Entry ",
                        "tenant_id": 10001,
                        "created_at": "2023-09-15T07:20:56.342Z",
                        "updated_at": "2023-09-15T07:21:55.479Z",
                        "description": null,
                        "rating": null,
                        "author_id": null,
                        "deleted": false,
                        "icon_name": null,
                        "icon_image": null,
                        "color": "#792d92",
                        "category_id": 1,
                        "status": "PUBLISHED",
                        "workflow_library_id": "75617639-3891-4e71-9150-e31bb5fe2be6"
                    }
                }
            },
            "assignee_users": [{
                "id": 10046,
                "full_name": "Mohib Habib",
                "email": "mohib.habib@venturenox.com",
                "job_title": null,
                "department": null,
                "organization": null,
                "image_url": "",
                "old_address": null,
                "country": null,
                "city": null,
                "birthday": null,
                "work_mode": null,
                "timezone": null,
                "slack": "U05QW8LE24C",
                "phone": null,
                "status": null,
                "state": null,
                "zip": null,
                "created_at": "2022-10-25T18:25:34.311Z",
                "updated_at": "2024-01-09T11:01:26.759Z",
                "deleted": false,
                "is_active": true,
                "address": null
            }],
            "user_profile": {
                "id": 10046,
                "full_name": "Mohib Habib",
                "email": "mohib.habib@venturenox.com",
                "job_title": null,
                "department": null,
                "organization": null,
                "image_url": "",
                "old_address": null,
                "country": null,
                "city": null,
                "birthday": null,
                "work_mode": null,
                "timezone": null,
                "slack": "U05QW8LE24C",
                "phone": null,
                "status": null,
                "state": null,
                "zip": null,
                "created_at": "2022-10-25T18:25:34.311Z",
                "updated_at": "2024-01-09T11:01:26.759Z",
                "deleted": false,
                "is_active": true,
                "address": null,
                "leave_requests": []
            },
            "depend_on_task": null,
            "client": {
                "id": 95,
                "company_name": "Production",
                "dba": "",
                "ein": "34-2424243",
                "business_type": "",
                "industry": "",
                "company_phone": null,
                "document_storage": null,
                "state": "Alabama",
                "date": "",
                "fiscal_year_end": null,
                "software": [],
                "close_week": null,
                "start_date": null,
                "notes": null,
                "city": null,
                "zip": null,
                "accounting": null,
                "created_at": "2022-12-29T11:08:44.770Z",
                "updated_at": "2023-12-13T12:58:01.602Z",
                "address": null,
                "ssn": null,
                "business_description": null,
                "website": null,
                "deleted": false,
                "payment_interval": null,
                "payment_interval_type": null,
                "payment_interval_rate": "0.00",
                "suit_floor": null,
                "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                "client_contact_list": [],
                "links": [],
                "team_client_permissions": [{
                    "id": 95,
                    "team_id": 18,
                    "client_id": 95,
                    "deleted": false,
                    "team": {
                        "id": 18,
                        "name": "Backend Team",
                        "tenant_id": 10001,
                        "description": "Team responsible for processing and string the data.",
                        "created_at": "2022-11-15T06:15:36.053Z",
                        "updated_at": "2023-07-25T11:35:51.768Z",
                        "deleted": false
                    }
                }]
            },
            "task_timers": [{
                "id": 36608,
                "user_id": 10046,
                "task_id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a",
                "consumed_time": "1001",
                "created_at": "2024-01-29T08:39:19.452Z",
                "updated_at": "2024-01-29T08:39:19.453Z",
                "logged_date": "2024-01-29T00:00:00.000Z",
                "timezone": "UTC",
                "user_profile": {
                    "id": 10046,
                    "full_name": "Mohib Habib",
                    "email": "mohib.habib@venturenox.com",
                    "job_title": null,
                    "department": null,
                    "organization": null,
                    "image_url": "",
                    "old_address": null,
                    "country": null,
                    "city": null,
                    "birthday": null,
                    "work_mode": null,
                    "timezone": null,
                    "slack": "U05QW8LE24C",
                    "phone": null,
                    "status": null,
                    "state": null,
                    "zip": null,
                    "created_at": "2022-10-25T18:25:34.311Z",
                    "updated_at": "2024-01-09T11:01:26.759Z",
                    "deleted": false,
                    "is_active": true,
                    "address": null
                }
            }, {
                "id": 36609,
                "user_id": 10002,
                "task_id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a",
                "consumed_time": "55000",
                "created_at": "2024-01-29T08:39:29.100Z",
                "updated_at": "2024-01-29T08:40:19.058Z",
                "logged_date": "2024-01-29T00:00:00.000Z",
                "timezone": "UTC",
                "user_profile": {
                    "id": 10002,
                    "full_name": "Nabeel Asif",
                    "email": "nabeel.asif@venturenox.com",
                    "job_title": null,
                    "department": null,
                    "organization": null,
                    "image_url": "https://levvy-data-prod.s3.us-west-1.amazonaws.com/web_images/1664277612464-cropped.jpg",
                    "old_address": null,
                    "country": null,
                    "city": null,
                    "birthday": "1997-09-17T00:00:00.000Z",
                    "work_mode": "null",
                    "timezone": "PST (UTC-08:00)(Idaho)",
                    "slack": "U06CP4VMY3W",
                    "phone": null,
                    "status": null,
                    "state": null,
                    "zip": null,
                    "created_at": "2022-07-08T19:43:23.143Z",
                    "updated_at": "2024-01-09T16:49:36.971Z",
                    "deleted": false,
                    "is_active": true,
                    "address": null
                }
            }],
            "comments": [],
            "dependent_task": {
                "id": "0d1eedcf-2e27-4de1-a32e-95b0c629db05",
                "task_type_id": 2,
                "client_workflow_task_id": 1647,
                "client_id": 95,
                "title": "Account Reconciliation",
                "due_date": "2024-01-31T00:00:00.000Z",
                "is_billable": true,
                "budgeted_hours": "1.00",
                "assignee_user_id": null,
                "dependent_task_id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a",
                "extended_date": null,
                "is_approval_required": false,
                "approval_from": null,
                "status": "NEW",
                "repeat_type": null,
                "repeat_interval": null,
                "is_new_task_created": false,
                "is_tentative": true,
                "description": "*Add Instructions.",
                "start_date": "2024-01-29T00:00:00.000Z",
                "notes": null,
                "workflow_recurrence_id": "c7055398-bee2-447b-af0e-f47ab60c63ec",
                "group_key": null,
                "dependancy_order": 0,
                "metadata": null,
                "type": null,
                "start_time": null,
                "end_time": null,
                "created_at": "2023-02-20T18:11:30.618Z",
                "updated_at": "2023-02-20T18:11:30.618Z",
                "agenda": null,
                "task_recurrence_id": null,
                "my_task": null,
                "task_recurrence": null,
                "client_workflow": {
                    "id": 484,
                    "workflow_id": 156,
                    "client_id": 95,
                    "version": 1.2,
                    "is_active": true,
                    "start_date": "2023-02-20T00:00:00.000Z",
                    "repeat_type": "WEEKLY",
                    "repeat_interval": 1,
                    "created_at": "2023-02-20T18:07:55.115Z",
                    "updated_at": "2023-09-15T07:21:54.804Z",
                    "is_monthly_on_day": false,
                    "recur_preference": null,
                    "end_on": {
                        "type": "never",
                        "occurrence": null,
                        "end_date": null
                    },
                    "deleted": false,
                    "required_days": 2,
                    "status": "active",
                    "display_name": "Data Entry  (2)",
                    "workflow": {
                        "id": 156,
                        "name": "Data Entry ",
                        "tenant_id": 10001,
                        "created_at": "2023-09-15T07:20:56.342Z",
                        "updated_at": "2023-09-15T07:21:55.479Z",
                        "description": null,
                        "rating": null,
                        "author_id": null,
                        "deleted": false,
                        "icon_name": null,
                        "icon_image": null,
                        "color": "#792d92",
                        "category_id": 1,
                        "status": "PUBLISHED",
                        "workflow_library_id": "75617639-3891-4e71-9150-e31bb5fe2be6"
                    },
                    "attachment": {
                        "id": "ea736471-55d6-45a2-acad-d4382dff114e",
                        "client_workflow_id": 484,
                        "sections": {
                            "folder": {
                                "default_folder_id": "6579abc1c79606c686cee88f",
                                "attached_ids": ["6579abc1c79606c686cee88f"]
                            }
                        },
                        "created_at": "2023-12-13T13:04:02.421Z",
                        "updated_at": "2023-12-13T13:04:02.422Z"
                    }
                },
                "task_assignees": [],
                "user_profile": null,
                "assignee_users": [],
                "client_workflow_task": {
                    "id": 1647,
                    "client_workflow_id": 484,
                    "task_type_id": 2,
                    "title": "Account Reconciliation",
                    "description": "*Add Instructions.",
                    "is_billable": true,
                    "budgeted_hours": "1.00",
                    "assignee_user_id": null,
                    "dependent_task_id": 1646,
                    "required_days": 2,
                    "approval_from": null,
                    "is_approval_required": false,
                    "deleted": false,
                    "order": 9,
                    "client_workflow": {
                        "id": 484,
                        "workflow_id": 156,
                        "client_id": 95,
                        "version": 1.2,
                        "is_active": true,
                        "start_date": "2023-02-20T00:00:00.000Z",
                        "repeat_type": "WEEKLY",
                        "repeat_interval": 1,
                        "created_at": "2023-02-20T18:07:55.115Z",
                        "updated_at": "2023-09-15T07:21:54.804Z",
                        "is_monthly_on_day": false,
                        "recur_preference": null,
                        "end_on": {
                            "type": "never",
                            "occurrence": null,
                            "end_date": null
                        },
                        "deleted": false,
                        "required_days": 2,
                        "status": "active",
                        "display_name": "Data Entry  (2)",
                        "workflow": {
                            "id": 156,
                            "name": "Data Entry ",
                            "tenant_id": 10001,
                            "created_at": "2023-09-15T07:20:56.342Z",
                            "updated_at": "2023-09-15T07:21:55.479Z",
                            "description": null,
                            "rating": null,
                            "author_id": null,
                            "deleted": false,
                            "icon_name": null,
                            "icon_image": null,
                            "color": "#792d92",
                            "category_id": 1,
                            "status": "PUBLISHED",
                            "workflow_library_id": "75617639-3891-4e71-9150-e31bb5fe2be6"
                        }
                    }
                },
                "depend_on_task": {
                    "id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a",
                    "task_type_id": 2,
                    "client_workflow_task_id": 1646,
                    "client_id": 95,
                    "title": "Data Entry",
                    "due_date": "2024-01-31T00:00:00.000Z",
                    "is_billable": true,
                    "budgeted_hours": "1.00",
                    "assignee_user_id": 10046,
                    "dependent_task_id": null,
                    "extended_date": null,
                    "is_approval_required": true,
                    "approval_from": 10002,
                    "status": "IN_PROGRESS",
                    "repeat_type": null,
                    "repeat_interval": null,
                    "is_new_task_created": false,
                    "is_tentative": false,
                    "description": "*Add Instructions",
                    "start_date": "2024-01-29T00:00:00.000Z",
                    "notes": null,
                    "workflow_recurrence_id": "c7055398-bee2-447b-af0e-f47ab60c63ec",
                    "group_key": null,
                    "dependancy_order": 0,
                    "metadata": null,
                    "type": null,
                    "start_time": null,
                    "end_time": null,
                    "created_at": "2023-02-20T18:11:30.618Z",
                    "updated_at": "2024-01-29T08:40:25.923Z",
                    "agenda": null,
                    "task_recurrence_id": null,
                    "user_profile": {
                        "id": 10046,
                        "full_name": "Mohib Habib",
                        "email": "mohib.habib@venturenox.com",
                        "job_title": null,
                        "department": null,
                        "organization": null,
                        "image_url": "",
                        "old_address": null,
                        "country": null,
                        "city": null,
                        "birthday": null,
                        "work_mode": null,
                        "timezone": null,
                        "slack": "U05QW8LE24C",
                        "phone": null,
                        "status": null,
                        "state": null,
                        "zip": null,
                        "created_at": "2022-10-25T18:25:34.311Z",
                        "updated_at": "2024-01-09T11:01:26.759Z",
                        "deleted": false,
                        "is_active": true,
                        "address": null
                    }
                },
                "client": {
                    "id": 95,
                    "company_name": "Production",
                    "dba": "",
                    "ein": "34-2424243",
                    "business_type": "",
                    "industry": "",
                    "company_phone": null,
                    "document_storage": null,
                    "state": "Alabama",
                    "date": "",
                    "fiscal_year_end": null,
                    "software": [],
                    "close_week": null,
                    "start_date": null,
                    "notes": null,
                    "city": null,
                    "zip": null,
                    "accounting": null,
                    "created_at": "2022-12-29T11:08:44.770Z",
                    "updated_at": "2023-12-13T12:58:01.602Z",
                    "address": null,
                    "ssn": null,
                    "business_description": null,
                    "website": null,
                    "deleted": false,
                    "payment_interval": null,
                    "payment_interval_type": null,
                    "payment_interval_rate": "0.00",
                    "suit_floor": null,
                    "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                    "client_contact_list": [],
                    "links": [],
                    "team_client_permissions": [{
                        "id": 95,
                        "team_id": 18,
                        "client_id": 95,
                        "deleted": false,
                        "team": {
                            "id": 18,
                            "name": "Backend Team",
                            "tenant_id": 10001,
                            "description": "Team responsible for processing and string the data.",
                            "created_at": "2022-11-15T06:15:36.053Z",
                            "updated_at": "2023-07-25T11:35:51.768Z",
                            "deleted": false
                        }
                    }]
                },
                "comments": [],
                "task_timers": []
            },
            "client_software_stacks": [{
                "id": 207,
                "client_id": 95,
                "type": "BANK_ACCOUNT",
                "created_at": "2022-12-29T11:09:53.443Z",
                "updated_at": "2022-12-29T11:10:15.306Z",
                "client": {
                    "id": 95,
                    "company_name": "Production",
                    "dba": "",
                    "ein": "34-2424243",
                    "business_type": "",
                    "industry": "",
                    "company_phone": null,
                    "document_storage": null,
                    "state": "Alabama",
                    "date": "",
                    "fiscal_year_end": null,
                    "software": [],
                    "close_week": null,
                    "start_date": null,
                    "notes": null,
                    "city": null,
                    "zip": null,
                    "accounting": null,
                    "created_at": "2022-12-29T11:08:44.770Z",
                    "updated_at": "2023-12-13T12:58:01.602Z",
                    "address": null,
                    "ssn": null,
                    "business_description": null,
                    "website": null,
                    "deleted": false,
                    "payment_interval": null,
                    "payment_interval_type": null,
                    "payment_interval_rate": "0.00",
                    "suit_floor": null,
                    "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                    "team_client_permissions": [{
                        "id": 95,
                        "team_id": 18,
                        "client_id": 95,
                        "deleted": false
                    }]
                },
                "softwares": [{
                    "account": "random_0.bwfxq3zeq5@gmail.com",
                    "custom_url": "http://www.bankofamerica.com",
                    "password": "U2FsdGVkX1+tu1iZKxtFcWH/N7uZwjzJGNdGXt+F0uPciFHoai2b9KkcUp4Vlkeh",
                    "id": 450,
                    "client_software_id": 207,
                    "notes": "",
                    "order": 0,
                    "role_id": 14,
                    "name": "BOA",
                    "institution_url_id": null
                }]
            }, {
                "id": 208,
                "client_id": 95,
                "type": "MERCHANT_ACCOUNT",
                "created_at": "2022-12-29T11:10:11.524Z",
                "updated_at": "2022-12-29T11:10:15.307Z",
                "client": {
                    "id": 95,
                    "company_name": "Production",
                    "dba": "",
                    "ein": "34-2424243",
                    "business_type": "",
                    "industry": "",
                    "company_phone": null,
                    "document_storage": null,
                    "state": "Alabama",
                    "date": "",
                    "fiscal_year_end": null,
                    "software": [],
                    "close_week": null,
                    "start_date": null,
                    "notes": null,
                    "city": null,
                    "zip": null,
                    "accounting": null,
                    "created_at": "2022-12-29T11:08:44.770Z",
                    "updated_at": "2023-12-13T12:58:01.602Z",
                    "address": null,
                    "ssn": null,
                    "business_description": null,
                    "website": null,
                    "deleted": false,
                    "payment_interval": null,
                    "payment_interval_type": null,
                    "payment_interval_rate": "0.00",
                    "suit_floor": null,
                    "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                    "team_client_permissions": [{
                        "id": 95,
                        "team_id": 18,
                        "client_id": 95,
                        "deleted": false
                    }]
                },
                "softwares": [{
                    "account": "random_0.k1we8vuf1nm@gmail.com",
                    "custom_url": "https://app.qbo.intuit.com/app/accountsettings?p=payments",
                    "password": "U2FsdGVkX18tbbKJ3q+hwLmEyry6BI5pqBJehFtJN6LTrDN50PAKzDEB/XBECqtd",
                    "id": 451,
                    "client_software_id": 208,
                    "notes": "",
                    "order": 0,
                    "role_id": 14,
                    "name": "IM",
                    "institution_url_id": null
                }]
            }, {
                "id": 205,
                "client_id": 95,
                "type": "SOFTWARE",
                "created_at": "2022-12-29T11:09:12.241Z",
                "updated_at": "2022-12-29T11:10:15.309Z",
                "client": {
                    "id": 95,
                    "company_name": "Production",
                    "dba": "",
                    "ein": "34-2424243",
                    "business_type": "",
                    "industry": "",
                    "company_phone": null,
                    "document_storage": null,
                    "state": "Alabama",
                    "date": "",
                    "fiscal_year_end": null,
                    "software": [],
                    "close_week": null,
                    "start_date": null,
                    "notes": null,
                    "city": null,
                    "zip": null,
                    "accounting": null,
                    "created_at": "2022-12-29T11:08:44.770Z",
                    "updated_at": "2023-12-13T12:58:01.602Z",
                    "address": null,
                    "ssn": null,
                    "business_description": null,
                    "website": null,
                    "deleted": false,
                    "payment_interval": null,
                    "payment_interval_type": null,
                    "payment_interval_rate": "0.00",
                    "suit_floor": null,
                    "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                    "team_client_permissions": [{
                        "id": 95,
                        "team_id": 18,
                        "client_id": 95,
                        "deleted": false
                    }]
                },
                "softwares": [{
                    "account": "random_0.xmfzigic73m@gmail.com",
                    "custom_url": "https://signin.online.adp.com/signin/v1/?APPID=HomepagePortal&productId=80e309c3-7078-bae1-e053-3505430b5495&returnURL=https://portal.adp.com/public/index.htm&callingAppId=HomepagePortal",
                    "password": "U2FsdGVkX1/vdFNnGuCR1cUMmfhCZxs3HgocmpvN/Q/YIKyBBPHKUCB46cS/nx2o",
                    "id": 448,
                    "client_software_id": 205,
                    "notes": "",
                    "order": 0,
                    "role_id": 14,
                    "name": "Payrol",
                    "institution_url_id": null
                }]
            }, {
                "id": 206,
                "client_id": 95,
                "type": "CREDIT_CARD_ACCOUNT",
                "created_at": "2022-12-29T11:09:34.206Z",
                "updated_at": "2022-12-29T11:10:15.310Z",
                "client": {
                    "id": 95,
                    "company_name": "Production",
                    "dba": "",
                    "ein": "34-2424243",
                    "business_type": "",
                    "industry": "",
                    "company_phone": null,
                    "document_storage": null,
                    "state": "Alabama",
                    "date": "",
                    "fiscal_year_end": null,
                    "software": [],
                    "close_week": null,
                    "start_date": null,
                    "notes": null,
                    "city": null,
                    "zip": null,
                    "accounting": null,
                    "created_at": "2022-12-29T11:08:44.770Z",
                    "updated_at": "2023-12-13T12:58:01.602Z",
                    "address": null,
                    "ssn": null,
                    "business_description": null,
                    "website": null,
                    "deleted": false,
                    "payment_interval": null,
                    "payment_interval_type": null,
                    "payment_interval_rate": "0.00",
                    "suit_floor": null,
                    "folder_id": "6579aa3dcbd9ae613ccc6ed7",
                    "team_client_permissions": [{
                        "id": 95,
                        "team_id": 18,
                        "client_id": 95,
                        "deleted": false
                    }]
                },
                "softwares": [{
                    "account": "random_0.214oinmzqs9@gmail.com",
                    "custom_url": "https://www.americanexpress.com/",
                    "password": "U2FsdGVkX1+Tv0k+0aJNe9a3WvF6GGtH1mkEq52JHoW1NDkk9v6V+Z20RxMP56Tu",
                    "id": 449,
                    "client_software_id": 206,
                    "notes": "",
                    "order": 0,
                    "role_id": 14,
                    "name": "Amerian Express",
                    "institution_url_id": null
                }]
            }]
        },
        "task_id": "2eec8dec-a3aa-4aa8-8c10-cf7a2547f10a"
    },
    "timestamp": 1706517630476
}

const data2 = {
	"user_id": 10002,
	"tenant_id": 10001,
	"role_scopes": [],
	"team_id": 18,
	"event": "user_created",
	"properties": {
		"task_id": "f1937695-1acd-4391-88ce-e97444022164",
		"user_id": 10002,
		"message": "17 okay",
		"attachment": "[]",
		"user_name": 'nabeel asif',
		"task_name":"Prepare offer letter",
        "message": "shani please work hard on the tickets that you are assigned",
		"client_name":"Production",
        "name": "mohib habib",
        "email": "link2ubaid98@gmail.com",

		"created_at": "2024-01-25T08:59:22.934Z",
		"id": 2119,
		"task": {
			"id": "f1937695-1acd-4391-88ce-e97444022164",
			"task_type_id": 2,
			"client_workflow_task_id": 1653,
			"client_id": 95,
			"title": "Prepare offer letter",
			"due_date": "2024-01-26T00:00:00.000Z",
			"is_billable": true,
			"budgeted_hours": "1.00",
			"assignee_user_id": 10046,
			"dependent_task_id": "e06f0d9f-ba9c-4467-9de0-2880900ec2e6",
			"extended_date": null,
			"is_approval_required": false,
			"approval_from": null,
			"status": "NEW",
			"repeat_type": null,
			"repeat_interval": null,
			"is_new_task_created": false,
			"is_tentative": false,
			"description": "*Add Instructions",
			"start_date": "2024-01-24T00:00:00.000Z",
			"notes": null,
			"workflow_recurrence_id": "6f6d7686-6158-4ddd-b288-495df873c53a",
			"group_key": null,
			"dependancy_order": 0,
			"metadata": null,
			"type": null,
			"start_time": null,
			"end_time": null,
			"created_at": "2023-04-05T20:09:16.627Z",
			"updated_at": "2024-01-24T19:28:16.076Z",
			"agenda": null,
			"task_recurrence_id": null
		},
		"user_profile": {
			"id": 10002,
			"full_name": "Nabeel Asif",
			"email": "nabeel.asif@venturenox.com",
			"job_title": null,
			"department": null,
			"organization": null,
			"image_url": "https://levvy-data-prod.s3.us-west-1.amazonaws.com/web_images/1664277612464-cropped.jpg",
			"old_address": null,
			"country": null,
			"city": null,
			"birthday": "1997-09-17T00:00:00.000Z",
			"work_mode": "null",
			"timezone": "PST (UTC-08:00)(Idaho)",
			"slack": "U06CP4VMY3W",
			"phone": null,
			"status": null,
			"state": null,
			"zip": null,
			"created_at": "2022-07-08T19:43:23.143Z",
			"updated_at": "2024-01-09T16:49:36.971Z",
			"deleted": false,
			"is_active": true,
			"address": null
		},
		"receivers": [10046,10214]
	},
	"timestamp": 1706173162955
}

module.exports = {data,data2};